
include:
  - infra-compose.yml

services:
  ingestion-service:
    build: 
      context: .
      dockerfile: ./ingestion-service/Dockerfile
    ports:
      - "5100:80"
    env_file:
      - local.env
      - ./.env
    environment:
      - ConnectionStrings__Postgres=Host=transactions-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  categorization-engine:
    build:
      context: .
      dockerfile: ./categorization-engine/Dockerfile
    ports:
      - "5212:80"
    env_file:
      - local.env
      - ./.env
    environment:
      - ConnectionStrings__Postgres=Host=transactions-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
  transaction-aggregator-api:
    build: 
      context: .
      dockerfile: ./Aggregator/Dockerfile
    ports:
      - "5050:80"
    env_file:
      - local.env
      - ./.env
    environment:
      - ConnectionStrings__Postgres=Host=transactions-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy



networks:
  default:
    name: aggregator-network
    driver: bridge
